### ISSUE TITLE
Error  reading lightmap

### ISSUE THREAD

**Issue by ghost** [maoserr/redshiftgui#13]
This standard line "map=177.00|100.00;3.00|100.00;-6.00|0.00;-174.00|0.00;" triggers this error:

PM:[opt_parse_map] Map empty.

removing the line fixes the issue.

issue exist  on manjaro xfce 32/64bit running as both root/user

**Comment by Nooby4Ever** [comment]
I'm having the same issue, it refuses to startup. Did not test the suggest fix.

**Comment by dileepmani** [comment]
change this line "map=177.00|100.00;3.00|100.00;-6.00|0.00;-174.00|0.00;" to "map=177.00,100.00;3.00,100.00;-6.00,0.00;-174.00,0.00;" (i.e replace | with ,) in  .redshiftgrc in home folder and save it.

**Comment by Nooby4Ever** [comment]
I can confirm the suggested solution works. Thanks!

**Comment by blasmat** [comment]
This solution works for me as well, but I am finding that it reverts itself so that I need to modify the map line in .redshiftgrc each time I want to start redshift.  Any permanent solution available?

**Comment by Nooby4Ever** [comment]
The file is indeed sometimes overwritten by redshift; i assume this line: [options.c 318](https://github.com/maoserr/redshiftgui/blob/6e0fb10642523bf26cc7f3d44e2ad3c703cc8d33/src/options.c#L318 ) must be changed to `while( (currstr=strchr(currstr,, ',') || currstr=strchr(currstr, '|')) ){ `as a workaround.  Or line [options.c 449](https://github.com/maoserr/redshiftgui/blob/6e0fb10642523bf26cc7f3d44e2ad3c703cc8d33/src/options.c#L449) to `fprintf(fid_config,"%.2f,%.2f;",Rs_opts.map[i].elev,Rs_opts.map[i].temp);`

Since i don't have time to test and make a PR myself i will leave  it to some one else.

**Comment by joksik** [comment]
sorry for refresh but i have the same error. solution works but maybe somebody will fix this?

**Comment by xorinet** [comment]
One simple solution would be to go to /usr/bin/redshiftgui, and add this line after `#!/bin/sh`:
`find ~/.redshiftgrc -type f -exec sed -i 's/|/,/g' {} \;`
This might not be a perfect solution, but at least it works :stuck_out_tongue: 

(sorry for saying this 3 or so years late)

**Comment by dag7dev** [comment]
@Xorinet no need to be sorry: I am here to write that as of 2022, this issue is still present.
