### ISSUE TITLE
Hide Tray Icon

### ISSUE THREAD

**Issue by WandersFar** [maoserr/redshiftgui#8]
Could we have the option to hide the tray icon?

I've been using this program for a couple years now, and I never turn it off or adjust the settings anymore, so it'd be nice if it could just run silently. Thanks for reading.

**Comment by BugZappr** [comment]
I suggest start another instance without a switch.  If it is running hidden, the new instance could terminate and the minimized instance would show.  Alternately, the new instance would terminate the hidden instance.  I've been tinkering around with a program of my own that behaves similarly.  I implemented it via shared memory and a named pipe.  It uses shared memory to see if an instance is already running, and a named pipe to communicate with it if it is.  I haven't run into an instance yet of blocking due to the pipe, although you have to be careful to flush and read it consistently.

Yet another option, but one I know nothing about from a programming standpoint, is running it as a service.  You would then load a GUI to control it.  Something similar can be seen in Hostman's server software (although I don't recommend it due to problems running Samba network discovery, which M$ calls something else, and a custom DNS client.)

(FWIW: I'd much rather have one less icon in the system tray, since I always have Windows show them all, than for it to respond to the weather, which has nothing to do with one's diurnal cycle.)
